name: Update

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: |
        cargo run --release
        cat OpenRCT2_header.asl OpenRCT2_post.asl > OpenRCT2.asl
    - name: Commit
      run: |
        if test -n "$(git status --porcelain)"; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add OpenRCT2.asl cache.ron
          git commit -m 'chore: update autosplitter script'
        fi
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
